stages:
  - build

package:
  stage: build
  image: python:3.7.13-slim-bullseye
  before_script:
    - apt update && apt install -y git
    - export TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
    - export VERSION="$TAG.$CI_PIPELINE_ID"
    - echo "Version is $VERSION"
    - echo "__version__ = \"$VERSION\"" > icescanner/version.py
  script:
    # build package
    - pip install build
    - python -m build
    # build dependencies
    - mkdir wheels
    - pip wheel -w wheels .
  artifacts:
    name: icescanner-$VERSION
    paths:
      - wheels
      - icescanner/config/main.yaml
    expire_in: "5d"
