stages:
  - pages

pages:
  stage: pages
  image: python:3.7.13-slim-bullseye
  before_script:
    - set
    - apt update && apt install -y git
    - pip install pipenv
    - pipenv install -d
  script:
    - pipenv run pdoc3 --html lib/
    - mv html public
  artifacts:
    paths:
      - public
