stages:
  - build

package:
  stage: build
  image: python:3.7.13-slim-bullseye
  before_script:
    - apt update && apt install -y git
    - export TAG=$(git describe --tags --abbrev=0)
    - export VERSION="$TAG.$CI_PIPELINE_ID"
    - echo "Version is $VERSION"
    - echo "__version__ = \"$VERSION\"" > icescanner/version.py
  script:
    - pip install build
    - python -m build
  artifacts:
    paths:
      - dist/*.whl
    expire_in: "5d"
