# port = left
# star = right
# stern = rear
# fore = front

common:
  server_ip: 192.168.0.168
  shot_frequency: 30s
  exposure: 1s
  root_dir: /opt/datasets

credentials:
  cameras: &default_camera_creds
    username: admin
    password: ice1ice2ice3

devices:
  cameras:
    port_camera:
      is_enabled: False
      ip: 192.168.1.1
    star_camera:
      is_enabled: False
      ip: 192.168.1.2
    stern_camera:
      is_enabled: False
      ip: 192.168.1.3
    fore_camera:
      is_enabled: False
      ip: 192.168.1.4
  lidars:
    port_lidar:
      is_enabled: True
      ip: 192.168.0.178
    star_lidar:
      is_enabled: True
      ip: 192.168.0.188
    stern_lidar:
      is_enabled: False
      ip: 192.168.1.7
    fore_lidar:
      is_enabled: False
      ip: 192.168.1.8
